import Foundation

/// How a `ScheduledBlock` came to exist. Stored on `ScheduledBlock.originRaw`
/// as `String` (SwiftData + CloudKit mirroring rejects enum-typed model
/// properties). Stable raw values — these land in CloudKit and must NEVER be
/// renamed without a migration.
public enum ScheduledBlockOrigin: String, Codable, Sendable, CaseIterable {
    /// Generated by the `DayScheduler` slot-fill.
    case auto
    /// The user added the block by hand (origin is preserved across re-plans).
    case manual
}
